-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with
-- 1 and 2
-- , the first 10
--  terms will be: 1,2,3,5,8,13,21,34,55,89

-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


FIBONUMBERS = {}

function fibo(n)
    if FIBONUMBERS[n] == nil then
        local result = 1
        if n == 1 then
            result = 1
        elseif n == 2 then
            result = 2
        else
            result = fibo(n - 1) + fibo(n - 2)
        end

        table.insert(FIBONUMBERS, result);
        return result
    end
    return FIBONUMBERS[n];
end

COUNT = 1
SUM = 0
while true do
    local value = fibo(COUNT)
    if value <= 4000000  then
        if value%2==0 then
            SUM = SUM + value    
        end
    else
        break
    end
    COUNT = COUNT + 1
end

print(SUM)
-- for i = 1, 10, 1 do
--     fibo(i)
-- end

-- for key, value in pairs(FIBONUMBERS) do
--     print(key,value)
-- end
